CREATE TABLE tbl_update_document_status (
   id  VARCHAR (64) NOT NULL,
   request_time datetime NOT NULL,
   document_number VARCHAR (10) NOT NULL,
   document_version VARCHAR (10) NOT NULL,
   fiscal_year VARCHAR (4) NULL,
   document_type VARCHAR (5) NOT NULL,
   sales_type VARCHAR (20) NOT NULL,
   product_group VARCHAR (20) NULL,
   customer_code VARCHAR (8) NOT NULL,
   document_date datetime NOT NULL,
   document_due_date datetime NOT NULL,
   po_number VARCHAR (35) NULL,
   group_number VARCHAR (20) NULL,
   document_amount decimal(19,2) NOT NULL,
   withholding_tax decimal(19,2) NULL,
   outstanding_amount decimal(19,2) NOT NULL,
   currency_code VARCHAR (3) NOT NULL,
   reference_number VARCHAR (10) NULL,
   document_status VARCHAR (10) NULL,
   failure_reason_code VARCHAR (6) NULL,
   failure_reason VARCHAR (255) NULL,
   transaction_number VARCHAR (20) NULL,
   debit_date datetime NULL ,
   debit_time datetime NULL ,
   payment_amount decimal(19,2) NULL,
   sponsor_bank_account decimal(19,2) NULL,
   bank_transaction_number VARCHAR (20) NULL,
   PRIMARY KEY(id));