CREATE TABLE `tbl_log_transaction` (
 `log_id` MEDIUMINT NOT NULL AUTO_INCREMENT,
 `log_type` VARCHAR(50) NOT NULL,
 `transaction_no` VARCHAR(50) NULL,
 `bank_code`  VARCHAR(50)  CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
 `sponsor_code` VARCHAR(20)  NULL,
 `sponsor_credit_limit_customer_id` VARCHAR(20)  NULL,
 `sponsor_credit_limit_account_type` VARCHAR(20)  NULL,
 `sponsor_credit_account_no` VARCHAR(20) NULL,
 `source_customer_id` VARCHAR(20)  NULL,
 `source_account_type` VARCHAR(20)  NULL,
 `source_account_no` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
 `destination_customer_id` VARCHAR(20) NULL,
 `destination_account_type`  VARCHAR(20) NULL,
 `destination_account_no` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL ,
 `transaction_date` VARCHAR(10) NULL,
 `transaction_amount` VARCHAR(20) NULL,
 `currency_code` VARCHAR(3) NULL,
 `transaction_status` VARCHAR(20) NOT NULL,
 `failure_reason_code` VARCHAR(255)  NULL,
 `failure_reason` VARCHAR(255)  NULL,
 `maturity_date` VARCHAR(10) NULL,
 `document_amount` VARCHAR(20) NULL,
 `finance_percent` VARCHAR(20) NULL,
 `bank_transaction_no` VARCHAR(50) NULL,
 `create_time` datetime NOT NULL,
 `create_by` MEDIUMINT NOT NULL,
 `update_time` DATETIME NOT NULL,
 `update_by` MEDIUMINT NOT NULL,
 `version` INT NOT NULL,
  PRIMARY KEY (`log_id`));