ALTER TABLE `tbl_user`
	ADD COLUMN   create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN   create_by MEDIUMINT,
	ADD COLUMN   update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN   birthday DATETIME,
	ADD COLUMN   last_login_date DATETIME,
	ADD COLUMN   update_by MEDIUMINT,
	ADD COLUMN   version INT DEFAULT 1;
